require 'pry'

module VcrCable
  class Railtie < Rails::Railtie
    initializer 'vcr_cable.insert_middleware' do |app|
      if VcrCable.enabled?
        app.config.middleware.use VCR::Middleware::Rack do |cassette, env|
          # TODO: I intend to build code that allows the cassette name to be either specified in the settings, or generated by a user-provided Proc.
          # Until then, I'm hard-coding my immediate need which is to find the cassette name from HTTP headers.
          vcr_context = env['HTTP_X_VCR_CONTEXT'] || 'DEFAULT'
          vcr_test = env['HTTP_X_VCR_TEST'] || 'DEFAULT'
          cassette.name "#{vcr_context}/#{vcr_test}"
          cassette.options :record => :new_episodes
        end
        VcrCable.configure_vcr
      end
    end
  end
end
