module VcrCable
  class Railtie < Rails::Railtie
    initializer 'vcr_cable.insert_middleware' do |app|
      if VcrCable.enabled?
        app.config.middleware.use VCR::Middleware::Rack do |cassette, env|
          # TODO: I intend to build code that allows the cassette name to be either specified in the settings, or generated by a user-provided Proc.
          # Until then, I'm just hard-coding my immediate need which is to use the HTTP Request Path as the cassette name.
          cassette.name "ROOT_#{env['PATH_INFO']}".gsub(/[^A-Za-z0-9]/, "_")
          cassette.options :record => :new_episodes
        end
        VcrCable.configure_vcr
      end
    end
  end
end
